#------INPUT-------
ROBERTA_DIM =  768 # FIXED BY RoBERTa
CATEGORY_EMB_DIM = 100
INPUT_DIM = ROBERTA_DIM + CATEGORY_EMB_DIM #868 
MAX_SEQ_LEN = 128 #PADDING

#----MODEL ARCHITECTURE-----
NUM_EXPERTS=4
NUM_HEADS=4
FFN_UNITS=INPUT_DIM # 868 — matches input dim, no bottleneck
EXPERT_OUT_DIM = INPUT_DIM * 2 # 1736 after dual pooling(max+avg)

#-------TRAINING-------
BATCH_SIZE=64
LEARNING_RATE=0.0001
DROPOUT=0.1
EPOCHS=30
PATIENCE=5

#-----LOSS------
ALPHA=0.7
BETA=0.3