#------INPUT-------
WORD_EMB_DIM =  300
CATEGORY_EMB_DIM = 100
INPUT_DIM = WORD_EMB_DIM + CATEGORY_EMB_DIM #400 
MAX_SEQ_LEN = 128 #PADDING

#----MODEL ARCHITECTURE-----
NUM_EXPERTS=4
NUM_HEADS=4
FFN_UNITS=400 
EXPERT_OUT_DIM = INPUT_DIM * 2 # 800 after dual pooling(max+avg)

#-------TRAINING-------
BATCH_SIZE=512
LEARNING_RATE=0.0003
DROPOUT=0.1
EPOCHS=25
PATIENCE=3

#-----LOSS------
ALPHA=0.7
BETA=0.3